# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Simple is double
email: ferlini.lam@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  On the engineering way.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ferlini.github.io" # the base hostname & protocol for your site
twitter_username: ferlini_lam
github_username:  Ferlini

# Build settings
markdown: kramdown
